testcne: fix ring api buffer overflow
Fix the following error found by gcc 12.2.0:

ring_api.c:654:15: error: ‘epoll_wait’ writing 24 bytes into a region\
 of size 12 overflows the destination [-Werror=stringop-overflow=]
                  rdy = epoll_wait(epfd, &ev, 2, 0);

The epoll_event list contains a single element, so it is wrong to expect
up to two.

Signed-off-by: Jeff Shaw <jeffrey.b.shaw@intel.com>